-- AULA 4 - DML
-- COMMIT E ROLLBACK

CREATE TABLE
    MATERIA (
        COD_MATERIA NUMBER,
        DESCRICAO VARCHAR2(20)
        );
        
INSERT INTO MATERIA
    VALUES (1, 'BANCO DE DADOS');

INSERT INTO MATERIA
    VALUES (2, 'BUSINES INTELIGENCE');
    
SELECT * FROM MATERIA;

COMMIT;

INSERT INTO MATERIA
    VALUES (3, 'BIG DATA');
    
-- ROLLBACK VOLTA TUDO ANTES DO COMMIT

ROLLBACK;    
    
-- INSERT    

ALTER TABLE CATEGORIA
    DROP CONSTRAINT CK_CATEGORIA;
    
INSERT INTO CATEGORIA
    (COD_CATEGORIA, CATEGORIA)
    VALUES (3, 'FRUTA');]
    
COMMIT;
    
-- INSERIR VARIAS LINHAS DE UMA VEZ

INSERT ALL
    INTO CATEGORIA VALUES (5, 'LEGUME')
    INTO CATEGORIA VALUES (6, 'CARNE')
    INTO CATEGORIA VALUES (7, 'GRAOS')
    INTO CATEGORIA VALUES (8, 'MERCEARIA')
SELECT ALL * FROM DUAL;
    
SELECT * FROM CATEGORIA;
    
-- A TABELA DUAL

SELECT SYSDATE FROM DUAL;
SELECT USER FROM DUAL;

-- DISPONIBILZA O PROXIMO VALOR DA SEQUNCIA

SELECT SEQ_CATEGORIA.NEXTVAL
    FROM DUAL;

-- APENAS EXIBE O VALOR ATUAL DISPONIVEL

SELECT SEQ_CATEGORIA.CURRVAL
    FROM DUAL;
    
-- INSERSAO COM VALORES NULOS

-- FORMA 1

INSERT INTO CATEGORIA
    (COD_CATEGORIA, CATEGORIA)
        VALUES (20, NULL);

-- FORMA 2

INSERT INTO CATEGORIA
    (COD_CATEGORIA)
        VALUES (30);
    
-- UPDATE

DROP TABLE PRODUTO CASCADE CONSTRAINTS;

CREATE TABLE
    PRODUTO (
        CODIGO INT CONSTRAINT PK_PRODUTO PRIMARY KEY,
        DESCRICAO VARCHAR(50),
        VALOR NUMBER(8,2)
        );
        
INSERT INTO PRODUTO VALUES (1010,'CAMISA',80.00);
INSERT INTO PRODUTO VALUES (1011,'POLO',120.00);
INSERT INTO PRODUTO VALUES (1012,'CAMISA',150.00);
INSERT INTO PRODUTO VALUES (1013,'CALCA',100.00);
INSERT INTO PRODUTO VALUES (1014,'SHORTS',70.00);
 

COMMIT;

UPDATE PRODUTO
    SET DESCRICAO = 'CAMISETA'
    WHERE CODIGO = 1010;
    
SELECT * FROM PRODUTO;

UPDATE PRODUTO
    SET VALOR = VALOR * 1.10;
    
UPDATE PRODUTO
    SET DESCRICAO = 'CALCA JEANS',
    VALOR = 150.00
        WHERE CODIGO = 1013;
        
-- DELETE
-- 1 LINHA

DELETE FROM PRODUTO
    WHERE CODIGO = 1013;
        
-- APOS COMMIT DADOS SERAO DELETADOS PERMANENTEMENTE

COMMIT;   
   
-- LINHAS QUE ATENDEM A CONDICAO DO WHERE 

DELETE FROM PRODUTO
    WHERE VALOR <= 100;
    
COMMIT;

SELECT * FROM PRODUTO;

DELETE FROM PRODUTO
    WHERE VALOR <= 135;
    
CREATE SEQUENCE SEQ_ERRO;

ROLLBACK;

-- ALTERANDO FORMATACAO DE DATA - APENAS NA SESSAO

ALTER SESSION
    SET NLS_DATE_FORMAT = 'DD/MM/YYYY';
    
-- ALTERANDO IDIOMA - APENAS NA SESSAO

ALTER SESSION
    SET NLS_DATE_LANGUAGE = 'PORTUGUESE';
    
SELECT
    SYSDATE,
    TO_CHAR(SYSDATE, 'MON') MESABV,
    TO_CHAR(SYSDATE, 'MONTH') MES
    FROM DUAL;
        
-- TABELAS DE DESCRICAO
-- MOSTRA TODOS OS OBJETOS PERTENCENTES AO USUARIO

SELECT * FROM USER_OBJECTS;

-- MOSTRA TODAS AS COLUNAS DE TODAS AS TABELAS DO USUARIO

SELECT * FROM USER_TAB_COLUMNS;
   
   
    